project:
  type: website
  resources: 
    - custom.scss
    - custom-light.scss
    - custom-dark.scss
#    scripts.js

freeze: true

website:
  title: "Harvey Lieberman"
  navbar:
    pinned: true
    left:
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: posts
    right:
      - text: "{{< li yvjimpju trigger=hover colors=primary:#ffffff,secondary:#c7e0eb >}}"
        href: https://github.com/harveyl888
      - text: "{{< li wlbymhoo trigger=hover colors=primary:#ffffff,secondary:#c7e0eb >}}"
        href: https://twitter.com/harveyl888
      - text: "{{< li qgebwute trigger=hover colors=primary:#ffffff,secondary:#c7e0eb >}}"
        href: https://www.linkedin.com/in/harvey-lieberman

format:
  html:
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    include-after-body:
      - text: |
          <script type="text/javascript" src="/_resources/js/scripts.js"></script>
    theme: 
      light: [flatly, custom.scss, custom-light.scss]
      dark: [darkly, custom.scss, custom-dark.scss]

