project:
  type: website

freeze: true

website:
  title: "Harvey Lieberman"
  navbar:
    pinned: true
    left:
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com
format:
  html:
    theme: cosmo
    css: styles.css



