project:
  type: website
  resources: 
    scripts.js

freeze: auto

website:
  title: "Harvey Lieberman"
  navbar:
    pinned: true
    left:
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: posts
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com

format:
  html:
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    include-after-body:
      - text: |
          <script type="text/javascript" src="/_resources/js/scripts.js"></script>
    theme: 
      - custom.scss

