---
author: "Harvey"
title: "In The Cloud"
date: "2017-02-21"
description: "I'm now totally cloud-based"
categories: ["Opinion"]
---

About 2 years ago my beloved Asus G60VX died.  I loved that laptop.  We'd been through a lot together and enjoyed five wonderful years.  After a brief mourn I had a long think about the future and decided to move to a Chromebook.  Precisely an Acer C270.  I've moved from 15"x10" (16" screen), 7.3lbs to 11"x8" (11.6" screen), 2.8lbs.  The Asus would run for an hour on its 6-cell battery whereas the Chromebook can hold a charge for 8 hours.  For storage I mostly use Google drive and for programming I use Codeanywhere and Digital Ocean droplets (along with firessh, caret and pixlr).  Total cost is minimal.  Everything I run or test is hosted remotely and internet is freely available almost everywhere - the few times I've been unable to connect, my cellphone has proved to be an adequate hotspot.  
If anything ever happens to my chromebook I could transition to another machine and continue where I left off as if nothing happened.  I'm totally cloud-based and loving it!
